### ISSUE TITLE
Bug on kernel

### ISSUE THREAD

**Issue by FndNur1Labs** [netcoinfoundation/netcoin#21]
![netcoinbug](https://user-images.githubusercontent.com/11433397/33103035-2d1f7220-cf63-11e7-81b6-e7f7117c23e3.png)

when i try open keep like that and replace old block run. when some new block found[some reason electric down]. it''s bug~

explain guys~

**Comment by regtable** [comment]
Did you have a power cut? I would guess that it has corrupted the database files you must replace those.

**Comment by BigJohnson124** [comment]
corrupted database with with a hard shutdown is my guess as well. Clean the files and start over or use the blockchain download to replace them.

**Comment by FndNur1Labs** [comment]
the long days shutdown. strom effect make it. thank guys all fixed keep back up files

**Comment by regtable** [comment]
Glad to know your back on track
