### ISSUE TITLE
bug balance gone

### ISSUE THREAD

**Issue by FndNur1Labs** [netcoinfoundation/netcoin#22]
![2](https://user-images.githubusercontent.com/11433397/42209381-74b6eb50-7ee9-11e8-9bf1-7720718a1636.png)
![0](https://user-images.githubusercontent.com/11433397/42209383-7508ed2e-7ee9-11e8-95b0-e55d50a828f8.png)

**Comment by regtable** [comment]
Could you let me know what you have done. Or what has happened to cause
this but? Such as restoring block data with snapshot. Or maybe replacing
wallet.dat with a back-up.dat. firstly I would close the wallet backup your
wallet.dat and chain data basically the whole netcoin folder in roaming.
Then once backed up (to a new location) do not overwrite an old back up,
try opening the wallet and typing checkwallet in the debug. If it comes
back as mismatch spent coins type repair wallet and those coins should show
back up. Also check block height against prohashing and the txid if it
shows there all is well. Keep us updated on findings.
Thanks
Regtable
