### ISSUE TITLE
Unable to compile.

### ISSUE THREAD

**Issue by miningpoolhub** [netcoinfoundation/netcoin#6]
I already compiled previous netcoin and about to update to latest but stuck.
I don't know why I see this weird encoding broken error messages.
Maybe you forgot to commit the updated file?

------ ERROR MESSAGE -------

-
/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DUSE_IPV6 -DBOOST_SPIRIT_THREADSAFE -I/home/ubuntu/walletsrc/netcoin/src -I/home/ubuntu/walletsrc/netcoin/src/obj -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/wallet.d -o obj/wallet.o wallet.cpp
In file included from net.h:17:0,
                 from main.h:13,
                 from db.h:9,
                 from txdb.h:11,
                 from wallet.cpp:9:
util.h: In function â€˜std::string i64tostr(int64_t)â€™:
util.h:262:12: warning: format â€˜%lldâ€™ expects argument of type â€˜long long intâ€™, but argument 3 has type â€˜int64_t {aka long int}â€™ [-Wformat]
In file included from main.h:13:0,
                 from db.h:9,
                 from txdb.h:11,
                 from wallet.cpp:9:
net.h: In member function â€˜void CNode::AskFor(const CInv&)â€™:
net.h:325:149: warning: format â€˜%lldâ€™ expects argument of type â€˜long long intâ€™, but argument 3 has type â€˜int64_t {aka long int}â€™ [-Wformat]
In file included from db.h:9:0,
                 from txdb.h:11,
                 from wallet.cpp:9:
main.h: In member function â€˜void CBlock::print() constâ€™:
main.h:1167:67: warning: format â€˜%lluâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 10 has type â€˜std::vector<CTransaction>::size_type {aka long unsigned int}â€™ [-Wformat]
main.h: In member function â€˜std::string CBlockIndex::ToString() constâ€™:
main.h:1423:16: warning: format â€˜%llxâ€™ expects argument of type â€˜long long unsigned intâ€™, but argument 13 has type â€˜uint64_t {aka long unsigned int}â€™ [-Wformat]
wallet.cpp: In member function â€˜bool CWallet::AddToWallet(const CWalletTx&)â€™:
wallet.cpp:543:27: error: â€˜wtxâ€™ was not declared in this scope
wallet.cpp:546:46: error: â€˜fInsertedNewâ€™ was not declared in this scope
wallet.cpp: At global scope:
wallet.cpp:557:5: error: expected unqualified-id before â€˜returnâ€™
wallet.cpp:558:1: error: expected declaration before â€˜}â€™ token
wallet.cpp: In member function â€˜bool CWallet::AddToWallet(const CWalletTx&)â€™:
wallet.cpp:556:5: warning: control reaches end of non-void function [-Wreturn-type]
make: *** [obj/wallet.o] Error 1

**Comment by Meee32** [comment]
Hi there, wow our first issue :)
Yeah we have been alerted to the problem and we're looking into it now. I think I may know what it is, just testing out the fix now but we'll get back to you asap. Thanks for letting us know.

**Comment by Meee32** [comment]
Issue is now resolved I just updated my pool :)

**Comment by miningpoolhub** [comment]
Thanks. it's working well!
